app_login:
    path: /login
    controller: App\Controller\SecurityController::login

index:
    path: /
    controller: App\Controller\DefaultController::index

article:
  path: /blog
  controller: App\Controller\ArticleController::index
